import type { Job } from './job'

const now  = new Date()
const mins = (n: number) => new Date(now.getTime() - n * 60_000)
const hrs  = (n: number) => new Date(now.getTime() - n * 3_600_000)

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    source: 'atriveo',
    title: 'Senior Product Designer',
    company: 'Linear',
    location: 'Remote · US',
    salary: '$150k – $190k',
    postedAt: mins(8),
    status: 'live',
    scorePct: 87,
    scoreDelta: +4,
    tags: ['Figma', 'Design Systems', 'B2B SaaS'],
    applyUrl: 'https://linear.app/careers',
    isHidden: false, isSaved: true, hasApplied: false, isImportant: true, isTopList: false,
    level: 'senior', jobType: 'full-time', workMode: 'remote',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Design complex workflows and developer tools at one of the fastest-growing productivity companies. You will work closely with engineering and product to define the future of project management.',
  },
  {
    id: '2',
    source: 'atriveo',
    title: 'Staff Product Designer',
    company: 'Vercel',
    location: 'Remote · Worldwide',
    salary: '$170k – $220k',
    postedAt: mins(22),
    status: 'live',
    scorePct: 79,
    scoreDelta: null,
    tags: ['Next.js', 'Dev Tools', 'Design Systems'],
    applyUrl: 'https://vercel.com/careers',
    isHidden: false, isSaved: false, hasApplied: false, isImportant: false, isTopList: false,
    level: 'staff', jobType: 'full-time', workMode: 'remote',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Shape the future of web development tooling. Own design across Vercel\'s deployment, analytics, and collaboration surfaces.',
  },
  {
    id: '3',
    source: 'atriveo',
    title: 'Senior UX Designer — Growth',
    company: 'Figma',
    location: 'San Francisco, CA',
    salary: '$165k – $195k',
    postedAt: mins(41),
    status: 'live',
    scorePct: 73,
    scoreDelta: -2,
    tags: ['Growth', 'Figma', 'Research'],
    applyUrl: 'https://figma.com/careers',
    isHidden: false, isSaved: false, hasApplied: false, isImportant: false, isTopList: false,
    level: 'senior', jobType: 'full-time', workMode: 'onsite',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Drive growth across Figma\'s free-to-paid conversion funnel. Run experiments, synthesise research, and collaborate with data science.',
  },
  {
    id: '4',
    source: 'atriveo',
    title: 'Product Designer II',
    company: 'Notion',
    location: 'Remote · US',
    salary: '$140k – $170k',
    postedAt: hrs(1),
    status: 'live',
    scorePct: 65,
    scoreDelta: null,
    tags: ['Productivity', 'Collaboration', 'B2C'],
    applyUrl: 'https://notion.so/careers',
    isHidden: false, isSaved: false, hasApplied: true, isImportant: false, isTopList: false,
    level: 'mid', jobType: 'full-time', workMode: 'remote',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Work on core editing and collaboration features used by millions of teams worldwide.',
  },
  {
    id: '5',
    source: 'atriveo',
    title: 'Lead Product Designer',
    company: 'Loom',
    location: 'Remote · US',
    salary: '$155k – $185k',
    postedAt: hrs(2),
    status: 'closing',
    scorePct: 58,
    scoreDelta: -6,
    tags: ['Video', 'Async Comms'],
    applyUrl: 'https://loom.com/careers',
    isHidden: false, isSaved: false, hasApplied: false, isImportant: false, isTopList: false,
    level: 'senior', jobType: 'full-time', workMode: 'remote',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Lead design for Loom\'s async video product. Define how teams communicate without meetings.',
  },
  {
    id: '6',
    source: 'atriveo',
    title: 'Principal Designer',
    company: 'Stripe',
    location: 'Remote · US / UK',
    salary: '$190k – $250k',
    postedAt: hrs(3),
    status: 'live',
    scorePct: 44,
    scoreDelta: null,
    tags: ['FinTech', 'API Design', 'Scale'],
    applyUrl: 'https://stripe.com/jobs',
    isHidden: false, isSaved: false, hasApplied: false, isImportant: false, isTopList: false,
    level: 'principal', jobType: 'full-time', workMode: 'hybrid',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Design payment infrastructure and developer experience at global scale.',
  },
  {
    id: '7',
    source: 'atriveo',
    title: 'UX Designer — AI Products',
    company: 'Anthropic',
    location: 'San Francisco, CA',
    salary: '$160k – $200k',
    postedAt: hrs(5),
    status: 'live',
    scorePct: 31,
    scoreDelta: +12,
    tags: ['AI/ML', 'Research', 'Consumer'],
    applyUrl: 'https://anthropic.com/careers',
    isHidden: false, isSaved: false, hasApplied: false, isImportant: false, isTopList: false,
    level: 'senior', jobType: 'full-time', workMode: 'onsite',
    resumeFile: 'Designer_Resume.pdf',
    description: 'Shape the experience of frontier AI products used by millions. Work at the intersection of safety and usability.',
  },
]
